server:
  port: 8081
spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    password: password
    username: postgres
    url: jdbc:postgresql://localhost:5432/yamb
  jpa:
    hibernate:
      ddl-auto: update
    generate-ddl: true
